### ISSUE TITLE
Examples include Touchscreen.h, which doesn't exist in this repository.

### ISSUE THREAD

**Issue by gsreeves** [Seeed-Studio/TFT_Touch_Shield_V1#2]
The examples in this repository include Touchscreen.h, an external library that is not part of the standard Arduino libraries. This repository should include that library, if legal, or reference it in Readme.

**Comment by Erutan409** [comment]
@gsreeves Did you ever get any resolution on this issue? If memory serves: the last I tried using it (months ago), I was also having the same issue.

**Comment by gsreeves** [comment]
I can compile with the adafruit touchscreen library, but I haven't tested much. https://github.com/adafruit/Touch-Screen-Library

**Comment by hazelduvall** [comment]
The adafruit Touch Screen library is the correct library to use with this shield. Constructor: `TouchScreen ts = TouchScreen(A3,A2,A1,A0,300);`
