### ISSUE TITLE
Mega PORT redo?

### ISSUE THREAD

**Issue by gemSquared** [Seeed-Studio/TFT_Touch_Shield_V1#3]
The direct ports for the Arduino MEGA 2560 may not be configured properly? I'm getting no signals on pins 2-7 ... 

P.S. Sorry if this is a little late. I know this product is outdated.

**Comment by gemSquared** [comment]
Actually xD I found my problem. In TFT.h, I had to change the first "#define SEEEDUINO" to "#define MEGA".
How do you change this in the arduino editor?

**Comment by KillingJacky** [comment]
Hi @gemSquared , though we can't edit the library file in Arduino IDE, we can navigate to the path of this file and edit it directly.

**Comment by gemSquared** [comment]
I was lazy and just copied the library and named it "TFT_MEGA" then added the changes. You're right about the MEGA being slower.
